apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pv-claim
  labels:
    app: minio-storage-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: zone2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi